<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Shashwat" name="framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2" tests="3" failures="0" timestamp="2021-09-22T21:12:33 IST" time="372.102" errors="1">
  <testcase name="loggedInCustomerOrder" time="218.126" classname="framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2">
    <skipped/>
  </testcase> <!-- loggedInCustomerOrder -->
  <testcase name="loggedInCustomerOrder" time="75.356" classname="framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at framework.utils.Reports.reportStep(Reports.java:72)
at framework.utils.Reports.reportStep(Reports.java:82)
at framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2.loggedInCustomerOrder(LoggedInCustomerOrder_PartyLite_Smoke_TC2.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loggedInCustomerOrder -->
  <testcase name="loggedInCustomerOrder" time="78.620" classname="framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2">
    <skipped/>
  </testcase> <!-- loggedInCustomerOrder -->
</testsuite> <!-- framework.test.LoggedInCustomerOrder_PartyLite_Smoke_TC2 -->
